"""make employee profile fields optional

Revision ID: 2837089a9bf8
Revises: 28fac4ba7ea3
Create Date: 2026-09-30 11:37:03.172471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2837089a9bf8'
down_revision: Union[str, Sequence[str], None] = '28fac4ba7ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'designation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'designation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
