"""add onboarding fields to employees

Revision ID: 84fe6650307b
Revises: 004cc7991674
Create Date: 2026-10-01 17:09:48.568293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84fe6650307b'
down_revision: Union[str, Sequence[str], None] = '004cc7991674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('personal_email', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('profile_completed_at', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'employees', ['created_by'], ['employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'created_by')
    op.drop_column('employees', 'profile_completed_at')
    op.drop_column('employees', 'personal_email')
    # ### end Alembic commands ###
