"""remove fields not in employee schema

Revision ID: 921aa7fd6264
Revises: 48802c901590
Create Date: 2026-10-05 15:48:59.254926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '921aa7fd6264'
down_revision: Union[str, Sequence[str], None] = '48802c901590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_created_by_fkey'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'created_by')
    op.drop_column('employees', 'personal_email')
    op.drop_column('employees', 'profile_completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('profile_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('personal_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('employees_created_by_fkey'), 'employees', 'employees', ['created_by'], ['employee_id'])
    # ### end Alembic commands ###
