"""add user status and last login

Revision ID: bd27b9b383c4
Revises: 07296c5a3f38
Create Date: 2026-09-28 13:00:18.722042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd27b9b383c4'
down_revision: Union[str, Sequence[str], None] = '07296c5a3f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true()
        )
    )

    op.add_column(
        'users',
        sa.Column(
            'last_login',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###